import streamlit as st
import pandas as pd
import numpy as np
import joblib

# Set professional wide layout
st.set_page_config(
    page_title="Dual-Pipeline Evaluation Sandbox",
    page_icon="🛡️",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Dark-mode fintech CSS styling
st.markdown("""
    <style>
    .main { background-color: #0e1117; }
    .stMetric { background-color: #1f2937; padding: 12px; border-radius: 8px; border: 1px solid #374151; }
    .correct-box { background-color: #065f46; color: #34d399; padding: 8px; border-radius: 5px; font-weight: bold; text-align: center; font-size: 13px; }
    .wrong-box { background-color: #991b1b; color: #f87171; padding: 8px; border-radius: 5px; font-weight: bold; text-align: center; font-size: 13px; }
    .pipeline-header { background-color: #1e293b; padding: 10px; border-radius: 5px; text-align: center; font-weight: bold; margin-bottom: 15px; border: 1px solid #475569; }
    .title-text { color: #f3f4f6; font-family: 'Helvetica Neue', sans-serif; font-weight: 800; }
    </style>
""", unsafe_allow_html=True)


@st.cache_resource
def load_bundle():
    try:
        return joblib.load('currency_sandbox_bundle.pkl')
    except Exception as e:
        st.error(f"Error loading bundle: {e}")
        return None


bundle = load_bundle()

if bundle is not None:
    # Unpack complete dual-pipeline architecture
    models_p1 = bundle['models_p1']
    scaler_p1 = bundle['scaler_p1']
    models_p2 = bundle['models_p2']
    scaler_p2 = bundle['scaler_p2']
    encoder = bundle['encoder']
    test_X = bundle['test_X']
    test_y = bundle['test_y']

    # --- MAIN HEADER AREA ---
    st.markdown("<h1 class='title-text'>🛡️ Comparative Evaluation Sandbox</h1>",
                unsafe_allow_html=True)
    st.markdown(
        "##### B.Sc. Computer Science Thesis | Head-to-Head Architectural Pipeline Assessment")
    st.markdown("---")

    # --- SIDEBAR CONTROL PANEL ---
    st.sidebar.markdown("### 🎛️ Control Center")
    row_options = list(range(len(test_X)))
    selected_idx = st.sidebar.selectbox("🎯 Choose Test Sample Row Index:", options=row_options,
                                        format_func=lambda x: f"Sample Row #{x}")

    # Fetch selected row data
    raw_row = test_X.iloc[[selected_idx]].copy()
    true_label = int(test_y.iloc[selected_idx])

    # --- TOP ROW: DATA VIEW & GROUND TRUTH ---
    col_a, col_b = st.columns([3, 1])
    with col_a:
        st.markdown("### 📋 Selected Raw Note Parameters")
        st.dataframe(raw_row, use_container_width=True)
    with col_b:
        st.markdown("### 🎯 True Answer")
        if true_label == 1:
            st.markdown(
                "<div style='font-size:20px; padding:15px;' class='wrong-box'>🔴 COUNTERFEIT NOTE</div>",
                unsafe_allow_html=True)
        else:
            st.markdown(
                "<div style='font-size:20px; padding:15px;' class='correct-box'>🟢 GENUINE NOTE</div>",
                unsafe_allow_html=True)

    st.markdown("---")

    # --- PROCESSING FEATURE SPACES EXPLICITLY ---
    # Prepare Pipeline 1 features (Target Encoding only)
    row_p1 = raw_row.copy()
    for col in ['Country', 'Denomination', 'SecurityFeatures']:
        row_p1[col] = encoder[col].get(raw_row[col].values[0], encoder['global_fallback'])
    scaled_features_p1 = scaler_p1.transform(row_p1)

    # Prepare Pipeline 2 features (Engineered + Target Encoding)
    row_p2 = raw_row.copy()
    row_p2['Volume'] = row_p2['Length'] * row_p2['Width'] * row_p2['Thickness']
    row_p2['DensityFactor'] = row_p2['Weight'] / (row_p2['Volume'] + 1e-8)
    row_p2['AspectRatio'] = row_p2['Length'] / (row_p2['Width'] + 1e-8)
    row_p2['Serial_Length'] = row_p2['SerialNumber'].astype(str).str.len()
    row_p2['Serial_Magnitude'] = np.log1p(row_p2['SerialNumber'])
    row_p2['Serial_Modulo_Check'] = row_p2['SerialNumber'] % 7

    for col in ['Country', 'Denomination', 'SecurityFeatures']:
        row_p2[col] = encoder[col].get(raw_row[col].values[0], encoder['global_fallback'])
    scaled_features_p2 = scaler_p2.transform(row_p2)

    # --- DYNAMIC FEATURE ENGINEERING METRICS VIEW ---
    st.markdown("### 🛠️ Pipeline 2 Real-Time Feature Extraction Audit")
    st.write(
        "These structural features are automatically generated by Pipeline 2 to expose hidden material science patterns:")

    col1, col2, col3, col4 = st.columns(4)
    col1.metric("Calculated 3D Volume", f"{row_p2['Volume'].values[0]:.4f}")
    col2.metric("Calculated Density Proxy", f"{row_p2['DensityFactor'].values[0]:.4f}")
    col3.metric("Geometric Aspect Ratio", f"{row_p2['AspectRatio'].values[0]:.4f}")
    col4.metric("Serial Number Modulo", f"{int(row_p2['Serial_Modulo_Check'].values[0])}")

    st.markdown("---")

    # --- THE COMPETITIVE COMPARISON VIEW ---
    st.markdown("### 🏎️ Side-by-Side Pipeline Performance Showdown")
    st.write("See how the models perform with raw columns vs. specialized engineered combinations:")

    # Create two large columns to host Pipeline 1 vs Pipeline 2 side by side
    left_pane, right_pane = st.columns(2)


    # Helper function to render model cards smoothly
    def render_pipeline_column(pane, title, models_dict, feature_matrix, color_hex):
        with pane:
            st.markdown(f"<div class='pipeline-header' style='color:{color_hex};'>{title}</div>",
                        unsafe_allow_html=True)

            for name, model in models_dict.items():
                pred = int(model.predict(feature_matrix)[0])
                is_correct = (pred == true_label)

                # Confidence grading
                if hasattr(model, "predict_proba"):
                    confidence = model.predict_proba(feature_matrix)[0][pred] * 100
                else:
                    decision_val = model.decision_function(feature_matrix)[0]
                    confidence = min(100.0, max(50.0, 50.0 + (abs(decision_val) * 10)))

                # Create a mini dashboard card for each classifier
                c1, c2 = st.columns([3, 2])
                with c1:
                    pred_str = "⚠️ Counterfeit" if pred == 1 else "✅ Genuine"
                    st.markdown(f"**{name}**")
                    st.caption(f"Output: {pred_str} ({confidence:.1f}% Conf.)")
                with c2:
                    if is_correct:
                        st.markdown("<div class='correct-box'>🏆 MATCH</div>",
                                    unsafe_allow_html=True)
                    else:
                        st.markdown("<div class='wrong-box'>❌ FAIL</div>", unsafe_allow_html=True)
                st.markdown("<div style='margin-bottom:8px;'></div>", unsafe_allow_html=True)


    # Render Pipeline 1 (Purple theme)
    render_pipeline_column(left_pane, "🟪 PIPELINE 1: BASELINE FEATURES", models_p1,
                           scaled_features_p1, "#9b59b6")

    # Render Pipeline 2 (Green theme)
    render_pipeline_column(right_pane, "🟩 PIPELINE 2: SPECIALIZED ENGINEERED FEATURES", models_p2,
                           scaled_features_p2, "#2ecc71")

else:
    st.warning(
        "🔄 System setup in progress. Please save 'currency_sandbox_bundle.pkl' into this directory path.")